name = "quran-apps-directory-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist/browser"

# Default build configuration
[build]
command = "npm run build:staging"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"
